### ISSUE TITLE
[Possible Bug] Payment link creation results in a 400(Bad Request) error

### ISSUE THREAD

**Issue by reignydeyz** [russkyc/paymongo-sharp#13]
First, I want to express my gratitude for the amazing work you’ve done on this project. I've been using the library for quite some time now and I find it really easy to use.

I am not sure whether Paymongo has changed something on their API because right now I am getting 400 (Bad request) when creating a Payment Link. Upon checking their API doc, I found out that the Amount is integer but the library has decimal datatype - which perhaps is the culprit.

https://developers.paymongo.com/reference/create-a-link

**Comment by russkyc** [comment]
Appreciate the love, thanks for letting me know about the issue @reignydeyz !

The difference in datatype is intentional, it is being converted by the client to the integer type that paymongo uses. Eg; 987.75 will be converted to 98775 or 300.00 will be converted to 30000 before being sent to the paymongo server and vice versa. This is a choice that is purely driven to better developer experience since decimals are a much better representation of monetary amounts in C#.

With the current tests it shows a passing result, although there might be an edge case at play.

![image](https://github.com/user-attachments/assets/2104c03c-4f0b-4566-9f81-0c3361d1cfff)

Could you send in a snippet of the code so I can test with the same scenario? Thanks!

**Comment by reignydeyz** [comment]
I tried testing it again, and I may have found the culprit.

This is how I do it...
```c#
return await _client.Links.CreateLinkAsync(new Link
{
    Amount = form.Amount / 100,
    Description = form.Description
});
```
Noticed I have to divide `amount` to `100` for PayMongo to get the correct value. If I don't do this, the transaction will push through but the `amount` is incorrect...
![image](https://github.com/user-attachments/assets/d7e1333b-8dbf-4fb9-8efb-bf9bbf882fe1)
- Given the image above, the actual `amount` passed is `80`, but PayMongo thinks it's `8000`

If the amount passed is lower than `100` it will throw an error and not push through.
![image](https://github.com/user-attachments/assets/6e36e94a-ea07-476e-9cd1-2974920375cb)

**Comment by russkyc** [comment]
Thanks for adding in the observations in addition to the code.

From what I can see in the case of the misrepresented amount (80 was read as 8000) it seems to be a problem with the decimal places.

This is how paymongo handles amount values (from docs):

![Screenshot_20240714-104311.jpg](https://github.com/user-attachments/assets/508d1c82-709b-4e7b-b354-d67d7ecee771)

Given this and the code snippet, the API interpreted the value 80.0000 as 8,000 because if translated to 800000 it would be read by paymongo as 8000.00 due to paymongo only accepting 2 decimal values.

limiting/rounding to 2 decimal places as stated in the docs would be the fix. 

The links resource also stated that the minimum amount for a link is 100, so unfortunately amounts under 100 cannot be processed by the links api.

**Comment by russkyc** [comment]
For this use case with items under 100 I would recommend using the checkout api instead as it supports amounts lower than 100.00. Do let me know if this fixes the issue for you

**Comment by reignydeyz** [comment]
Thanks for the quick response. I may have overlooked the API doc and didn't notice the minimum amount required. 

I have adjusted my logic to only allow minimum transaction amount of `100`.

I've checked the Checkout API and I'm afraid it doesn't have the flexibility as Link's.

Appreciate your kind support. Consider to issue closed.

**Comment by reignydeyz** [comment]
Thanks for the quick response. I may have overlooked the API doc and didn't notice the minimum amount required. 

I have adjusted my logic to only allow minimum transaction amount of `100`.

I've checked the Checkout API and I'm afraid it doesn't have the flexibility as Link's.

Appreciate your kind support. Consider the issue closed.
